/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Paneles;

import Clases.Pregunta;

/**
 *
 * @author Alejandro
 */
public class PanelPregunta extends javax.swing.JPanel {

    /**
     * Creates new form PanelPregunta
     */
    public PanelPregunta(Pregunta p) {
        initComponents();
        labelPregunta.setText(p.getPregunta());
        radioRespuesta1.setText(p.getListRespuestas().get(0).getRespuesta());
        radioRespuesta2.setText(p.getListRespuestas().get(1).getRespuesta());
        radioRespuesta3.setText(p.getListRespuestas().get(2).getRespuesta());
        radioRespuesta4.setText(p.getListRespuestas().get(3).getRespuesta());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRespuestas = new javax.swing.ButtonGroup();
        labelPregunta = new javax.swing.JLabel();
        radioRespuesta1 = new javax.swing.JRadioButton();
        radioRespuesta2 = new javax.swing.JRadioButton();
        radioRespuesta3 = new javax.swing.JRadioButton();
        radioRespuesta4 = new javax.swing.JRadioButton();

        labelPregunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPregunta.setText("¿Pregunta?");

        grupoRespuestas.add(radioRespuesta1);
        radioRespuesta1.setText("respuesta 1");

        grupoRespuestas.add(radioRespuesta2);
        radioRespuesta2.setText("respuesta 2");

        grupoRespuestas.add(radioRespuesta3);
        radioRespuesta3.setText("respuesta 3");

        grupoRespuestas.add(radioRespuesta4);
        radioRespuesta4.setText("respuesta 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioRespuesta2)
                            .addComponent(radioRespuesta1)
                            .addComponent(radioRespuesta3)
                            .addComponent(radioRespuesta4))))
                .addGap(274, 274, 274))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {radioRespuesta1, radioRespuesta2, radioRespuesta3, radioRespuesta4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioRespuesta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioRespuesta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioRespuesta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioRespuesta4)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {radioRespuesta1, radioRespuesta2, radioRespuesta3, radioRespuesta4});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoRespuestas;
    private javax.swing.JLabel labelPregunta;
    private javax.swing.JRadioButton radioRespuesta1;
    private javax.swing.JRadioButton radioRespuesta2;
    private javax.swing.JRadioButton radioRespuesta3;
    private javax.swing.JRadioButton radioRespuesta4;
    // End of variables declaration//GEN-END:variables
}
